doctor/urls.py
from django.conf.urls import url

from doctor import utils
from . import views

app_name = 'doctor'
urlpatterns = [
    url(r'^doctor/(?P<doctor_id>[0-9]+)/$', views.homepage, name='homepage_doc'),
    url(r'^doctor/(?P<doctor_id>[0-9]+)/makeappointment/$', views.MakeAppointmentView.as_view(),
        name='make_appointment'),
    url(r'^doctor/(?P<doctor_id>[0-9]+)/patients$', views.PatientsPreviewView.as_view(), name='patients_preview'),
    url(r'^doctor/(?P<doctor_id>[0-9]+)/oldAppointments/$', views.OldAppointmentsView.as_view(),
        name='old_appointments'),
    url(r'^doctor/(?P<doctor_id>[0-9]+)/upcomingAppointments/$', views.UpcomingAppointmentsView.as_view(),
        name='upcoming_appointments'),
    url(r'^doctor/(?P<doctor_id>[0-9]+)/(?P<patient_id>[0-9]+)/$', views.patientDetails, name='patientDetails'),
    url(r'^doctor/(?P<doctor_id>[0-9]+)/appointment/(?P<appointment_id>[0-9]+)/$', views.appointment_details, name='appointment_details'),
    url(r'^doctor/(?P<doctor_id>[0-9]+)/appointment/(?P<appointment_id>[0-9]+)/addReport/', views.AddReportView.as_view(), name='add_report'),
    url(r'^ajax/get_times_available/$', views.get_times_available, name='times_available'),
    url(r'^ajax/get_doctors_for_hospital/$', utils.get_doctors_for_hospital, name='get_doctors_for_hospital'),
    url(r'^ajax/remove_self_as_gp/$', utils.remove_self_as_gp, name='remove_self_as_gp'),
    url(r'^ajax/add_self_as_gp/$', utils.add_self_as_gp, name='add_self_as_gp'),
    url(r'^ajax/remove_report_from_appointment/$', utils.remove_report_from_appointment, name='remove_report'),
    url(r'^ajax/get_patient_list/$', utils.get_patients_list, name='patient_list'),
    url(r'^ajax/get_appointments_list/$', utils.get_appointments_list, name='appointments_list'),
    url(r'^ajax/patient_apps_list/$', utils.get_patient_apps_list, name='patient_apps_list'),
    url(r'^ajax/add_gp_appointment/$', utils.add_gp_appointment, name='add_gp_appointment')
]

# /ajax/get_times_available/

ezdravstvo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls', namespace="login")),
    url(r'^', include('patient.urls', namespace="patient")),
    url(r'^', include('doctor.urls', namespace="doctor"))
]

login/urls.py
from django.conf.urls import url

from login import utils
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.UserFormView.as_view(), name='index'),
    url(r'^welcome/$', views.homepage, name='homepage'),
    url(r'^logout/$', views.logout_view, name='logout_user'),
    url(r'^registerPatient/$', views.PatientRegistrationView.as_view(), name='register_patient'),
    url(r'^registerDoctor/$', views.DoctorRegistrationView.as_view(), name='register_doctor'),
    url(r'^ajax/get_gps_for_hospital/$', utils.get_gps_for_hospital, name='get_gps_for_hospital'),
    url(r'^ajax/change_user_password/$', utils.change_user_password, name='change_user_password'),
]

doctor/models.py
from django.db import models

# Create your models here.

doctor/forms.py
from django import forms

from login.models import Doctor, Patient, Appointment, Report, Hospital
from doctor.utils import get_list_dates
from login.forms import ChoiceFieldNoValidation


class AppointmentForm(forms.ModelForm):
    hospital = forms.ModelChoiceField(label="Здравствена установа", required=False,
                                      queryset=Hospital.objects.all(),
                                      widget=forms.Select(attrs={'onchange': 'get_doctors_for_hospital()'}))
    doctor = forms.ModelChoiceField(label="Доктор", required=True,
                                    queryset=Doctor.objects.filter(is_general_practitioner=False))
    date2 = ChoiceFieldNoValidation()
    time2 = ChoiceFieldNoValidation(label='Време')

    def __init__(self, *args, **kwargs):  # we give the id of the doctor that will make the appointment. He can make appointments for only his patients
        if 'doctor_id' not in kwargs:
            super(AppointmentForm, self).__init__(*args, **kwargs)
            return

        self.doctor_id = kwargs.pop('doctor_id')
        super(AppointmentForm, self).__init__(*args, **kwargs)
        self.fields['patient'] = forms.ModelChoiceField(label="Пациент", required=True, queryset=Patient.objects.filter(
                            general_practitioner__doctor_id=self.doctor_id))

        # self.doctor_id = doctor_id
        # self.fields['patient'] = ChoiceFieldNoValidation(label="Пациент", required=True, choices=Patient.objects.filter(general_practitioner__doctor_id=self.doctor_id))

        choices_dates = get_list_dates(14)
        blank_choice = ('', '---------')
        choices_dates.insert(0, blank_choice)

        self.fields['date2'] = ChoiceFieldNoValidation(
            label="Датум",
            choices=choices_dates,
            required=True,
            widget=forms.Select(attrs={'onchange': 'make_change()'})
        )

    class Meta:
        model = Appointment
        fields = [
            'hospital', 'doctor', 'patient', 'date2', 'time2'
        ]


class AddReportForm(forms.ModelForm):
    therapy = forms.CharField(label="Терапија", max_length=200, required=False)
    remark = forms.CharField(label="Забелешка", max_length=200, required=False)

    class Meta:
        model = Report
        fields = ['diagnosis', 'therapy', 'remark']
        labels = {
            'diagnosis': 'Дијагноза'
        }

doctor/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import JsonResponse
from django.shortcuts import render, redirect
# from .forms import UserLoginForm
from django.utils.decorators import method_decorator
from django.views.generic import View

from doctor.forms import AppointmentForm, AddReportForm
from doctor.utils import get_apps_times_for_date
from login.models import Patient, Doctor, Appointment


# from .forms import UserForm, PatientRegistrationForm, DoctorRegistrationForm
# from .utils import add_general_practitioner


@login_required(login_url='login:index')  # With this, if no user is logged in, than you will be redirected to the login page
def homepage(request, doctor_id):
    patient_count = 0
    # context = {
    #     'patient_count': patient_count,
    #     'username': request.user.get_username(),
    #     'password': request.user.password,
    #     'doc_ID': request.user.doctor.doctor_id
    # }

    # TODO =============================================================================================================
    doctor = Doctor.objects.get(user__pk=request.user.id)
    if not doctor.is_general_practitioner:
        apps = Appointment.objects.filter(doctor__user__id=request.user.id).exclude(has_report_added=False)
        old_appointments = doctor.appointment_set.exclude(has_report_added=False)
        upcoming_appointments = doctor.appointment_set.filter(has_report_added=False)
        patients = set()
        for app in apps:
            patients.add(app.patient)

        context = {
            'doctor': doctor,
            'doctors_patients': patients,
            'old_appointments': old_appointments,
            'upcoming_appointments': upcoming_appointments
        }
        return render(request, 'doctor/homepage_doctor_not_gp.html', context)
    else:

        doctors_patients = doctor.patient_set.all()
        patients_without_gp = Patient.objects.filter(general_practitioner=None)
        context = {
            'doctor': doctor,
            'doctors_patients': doctors_patients,
            'patients_without_gp': patients_without_gp
        }
        return render(request, 'doctor/homepage_doctor_gp.html', context)
    # TODO =============================================================================================================
    # if request.user.doctor.is_general_practitioner:
    #     return render(request, 'doctor/homepage_doctor_gp.html', context)
    #
    # return render(request, 'doctor/homepage_doctor_not_gp.html', context)


@login_required(login_url='login:index')  # With this, if no user is logged in, than you will be redirected to the login page
def get_times_available(request):
    year = request.GET.get('year', None)
    month = request.GET.get('month', None)
    day = request.GET.get('day', None)
    doctor = request.GET.get('doctor', None)

    list_all_times = get_apps_times_for_date()

    apps = Appointment.objects.filter(doctor__id=doctor).filter(date__day=day, date__month=month, date__year=year)
    print("There are " + str(len(apps)) + " apps on that date\n\n\n\n\n")

    for app in apps:
        print(app)
        print(app.doctor.id)
        print("App hour: " + str(app.time.hour))
        print("App min: " + str(app.time.minute))

    times_free_list = list()

    # Malce e shabanski, ama fuck it
    for time in list_all_times:
        tmp = time[1].split(':')    # parse hour and min from string object
        hour = int(tmp[0])
        min = int(tmp[1])

        time_available = True

        for app in apps:
            if int(app.time.hour) == hour and int(app.time.minute) == min:
                time_available = False
                break

        if time_available:
            times_free_list.append(time)

    data = {
        'times': times_free_list
    }
    return JsonResponse(data)


class MakeAppointmentView(View):
    form_class = AppointmentForm
    template_name = 'doctor/appointment.html'

    @method_decorator(login_required(login_url='login:index'))
    def get(self, request, doctor_id):
        # doctor_id can be removed from the url here
        form = self.form_class(doctor_id = request.user.doctor.doctor_id)

        return render(request, self.template_name, {'form': form})

    @method_decorator(login_required(login_url='login:index'))
    def post(self, request, doctor_id):
        form = self.form_class(data=request.POST)

        if form.is_valid():
            print(form.cleaned_data.get('doctor').id)
            print(form.cleaned_data.get('patient'))
            date = str(form.cleaned_data.get('date2')).split(' ')[0]
            print(date)
            print(form.cleaned_data.get('time2'))
            appointment = Appointment(doctor=form.cleaned_data.get('doctor'),
                                      patient=form.cleaned_data.get('patient'),
                                      date=date,
                                      time=form.cleaned_data.get('time2'))
            appointment.save()
            print("App saved")
            return redirect('/doctor/' + str(request.user.id) + '/')
        else:
            print("Invalid form")

        return render(request, self.template_name, {'form': form})


class PatientsPreviewView(View):
    template_name = 'doctor/patients_preview.html'

    @method_decorator(login_required(login_url='login:index'))
    def get(self, request, doctor_id):
        doctor = Doctor.objects.get(user__pk=request.user.id)
        if not doctor.is_general_practitioner:
            apps = Appointment.objects.filter(doctor__user__id=request.user.id).exclude(has_report_added=False)
            patients = set()
            for app in apps:
                patients.add(app.patient)

            context = {
                'doctor': doctor,
                'doctors_patients': patients
            }
            return render(request, 'doctor/specialist_patient_preview.html', context)

        doctors_patients = doctor.patient_set.all()
        patients_without_gp = Patient.objects.filter(general_practitioner=None)
        context = {
            'doctor': doctor,
            'doctors_patients': doctors_patients,
            'patients_without_gp': patients_without_gp
        }
        return render(request, self.template_name, context)

    def post(self, request, doctor_id):
        pass


# TODO Check query for general practitioners
class OldAppointmentsView(View):
    template_name = 'doctor/old_appointments.html'

    @method_decorator(login_required(login_url='login:index'))
    def get(self, request, doctor_id):
        doctor = Doctor.objects.get(user__pk=request.user.id)
        # appointments = doctor.appointment_set.filter(date__lt=datetime.date.today())
        appointments = doctor.appointment_set.exclude(has_report_added=False)
        context = {
            'doctor': doctor,
            'appointments': appointments
        }
        return render(request, self.template_name, context)

    def post(self, request, doctor_id):
        pass


class UpcomingAppointmentsView(View):
    template_name = 'doctor/upcoming_appointments.html'

    @method_decorator(login_required(login_url='login:index'))
    def get(self, request, doctor_id):
        doctor = Doctor.objects.get(user__pk=request.user.id)
        # appointments = doctor.appointment_set.exclude(date__lt=datetime.date.today())
        appointments = doctor.appointment_set.filter(has_report_added=False)
        context = {
            'doctor': doctor,
            'appointments': appointments
        }
        return render(request, self.template_name, context)

    def post(self, request, doctor_id):
        pass


class AddReportView(View):
    form_class = AddReportForm

    @method_decorator(login_required(login_url='login:index'))
    def get(self, request, doctor_id, appointment_id):
        form = self.form_class(None)
        return render(request, 'doctor/add_report.html', {'form': form})

    @method_decorator(login_required(login_url='login:index'))
    def post(self, request, doctor_id, appointment_id):
        try:
            appointment = Appointment.objects.get(pk=appointment_id)
            form = self.form_class(request.POST)
            report = form.save(commit=False)
            report.appointment = appointment
            report.save()
            appointment.has_report_added = True
            appointment.save()
            return redirect('doctor:appointment_details', doctor_id=doctor_id, appointment_id=appointment_id)
        except Appointment.DoesNotExist:
            return Http404("Не постои прегледот!")


@login_required(login_url='login:index')
def appointment_details(request, doctor_id, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)

    try:
        if request.user.patient:
            # If the program comes here, than a patient tries to get access to doctor view. That can't happen
            return Http404("Access denied")

    except Exception as e:
        # a doctor is trying to access app details as he should
        pass

    context = {
        'appointment': appointment
    }
    return render(request, 'doctor/appointment_details.html', context)


@login_required(login_url='login:index')
def patientDetails(request, doctor_id, patient_id):
    patient = Patient.objects.get(user__id=patient_id)
    appointments = Appointment.objects.filter(patient__user__id=patient_id)     # list of all doctors that the patinet had a appointment with

    past_appointments = Appointment.objects.filter(patient__user__id=patient_id).exclude(has_report_added=False)
    future_appointments = Appointment.objects.filter(patient__user__id=patient_id).filter(has_report_added=False)

    context = {
        'patient': patient,
        'past_appointments': past_appointments,
        'future_appointments': future_appointments
    }

doctor/templates/doctor/add_report.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'doctor/doctor_style.css' %}"/>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Внеси извештај</title>

    <style>
        input{
            float:right;
            font-size: 20px;
        }

        select{
            float: right;
            margin-left: 5px;
        }

        form{
            padding: 30px;
            font-size: 25px;
            margin-left: 5%;
        }
    </style>

</head>
<body>

<div id="body_container">
    <div id="toolbar">
        <div style="display: inline-block; width: 50%;" >
            <h1 style="padding-left: 30px; color: darkblue">{{ request.user.doctor }}</h1>
        </div>

        <div class="toolbar_links">
            <button onClick="javascript:history.go(-1);" style="float: right;">
                    Назад
            </button>
        </div>

        <div class="toolbar_links" style="width: 20%">
            <a href="{% url 'login:logout_user' %}"><button style="display: block;">Одјави се</button></a>
        </div>
    </div>

    <div id="information_container">
        <h3 style="margin-left: 8%">Нов извештај</h3>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="present_button" type="submit">Потврди</button>
        </form>
    </div>

</div>

</body>
</html>

doctor/templates/doctor/appointment.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'doctor/doctor_style.css' %}"/>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Преглед</title>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

    <style>
        input{
            float:right;
            font-size: 20px;
        }

        select{
            float: right;
            margin-left: 5px;
        }

        form{
            padding: 30px;
            font-size: 25px;
            margin-left: 5%;
        }
    </style>

</head>
<body>
<div id="body_container">

    <div id="toolbar">
        <div style="display: inline-block; width: 60%;" >
            <h1 style="padding-left: 30px; color: darkblue">{{request.user.doctor}}</h1>
        </div>

        <div class="toolbar_links">
            <button onClick="javascript:history.go(-1);" style="float: right;">
                    Назад
            </button>
        </div>
        <div class="toolbar_links" style="width: 20%">
            <a href="{% url 'login:logout_user' %}"><button style="display: block;">Одјави се</button></a>
        </div>
    </div>

    <div id="information_container">
        <form id="app_form_id" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button id="button_app" type="submit">Закажи преглед</button>
        </form>
    </div>


</div>
<script>

    function get_doctors_for_hospital() {
        var hospital_ddl = $('#id_hospital');
        var selected = hospital_ddl.find(":selected").val();
        if (selected == "") {
            selected = "all";
        }
        var doctor_ddl = $('#id_doctor');
        console.log(selected);
        $.ajax({
            url: '{% url 'doctor:get_doctors_for_hospital' %}',
            data: {
                'hospital_id': selected
            },
            dataType: 'json',
            success: function (data) {
                var html_text = "";
                for (var i = 0; i < data.length; i++) {
                    var doc = data[i];
                    var id = doc['id'];
                    var name = doc['name'];
                    var option = "<option value=\"" + id + "\">" + name + "</option>" + "<br/>";
                    html_text += option;
                }
                doctor_ddl.html(html_text)
            }
        })
    }

    function make_change() {
        console.log("YEAH, this function is called. I am gonna retrieve available times for apps for the chosen date.")

        $('#id_time2').empty();
        var date_selected = $('#id_date2').find(":selected").text();
        var date_parsed = date_selected.split('-');
        var year = date_parsed[0]
        var month = date_parsed[1]
        var day = date_parsed[2]

        var doctor_selected = $('#id_doctor').val();
        {# returns primary key of doctor  #}

        $.ajax({
            url: '/ajax/get_times_available/',
            data: {
                'year': year,
                'month': month,
                'day': day,
                'doctor': doctor_selected
            },
            dataType: 'json',
            success: function (data) {
                console.log("Ajax function finished successfully")
                console.log(data.times)

                data.times.forEach(function (element) {
                    {#                       console.log(element[1]);#}
                    $('#id_time2').append($('<option>', {
                        value: element[0],
                        text: element[1]
                    }));
                });
            }
        });

        console.log("Finished adding values")
    }


</script>
</body>
</html>

doctor/templates/doctor/appointment_details.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'doctor/doctor_style.css' %}"/>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Детали</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
</head>
<body>

<div id="body_container">

    <div id="toolbar">
        <div style="display: inline-block; width: 50%;" >
            <h1 style="padding-left: 30px; color: darkblue">{{ appointment.patient }}</h1>
        </div>

        <div class="toolbar_links">
{#            <button onClick="javascript:history.go(-1);" style="float: right;">#}
{#                    Назад#}
{#            </button>#}
            <a href="{% url 'doctor:homepage_doc' doctor_id=request.user.doctor.id %}"><button style="display: block;">Назад</button></a>
        </div>

        <div class="toolbar_links" style="width: 20%">
            <a href="{% url 'login:logout_user' %}"><button style="display: block;">Одјави се</button></a>
        </div>
    </div>

    <div id="information_container">
        <h2>Детали за преглед #{{ appointment.appointment_number }}</h2>
        <div class="app_cont">
            <h3>Информации за пациентот</h3>
            <div>
                <div class="info_container">
                    <div class = "label_info"> Пациент: </div>
                    <div class="pers_info"> {{ appointment.patient }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Матичен број: </div>
                    <div class="pers_info"> {{ appointment.patient.ssn }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Прегледот го извршил: </div>
                    <div class="pers_info"> {{ appointment.doctor }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Датум: </div>
                    <div class="pers_info"> {{ appointment.date }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Час: </div>
                    <div class="pers_info"> {{ appointment.time }} </div>
                </div>


            </div>
        </div>
        <div class="app_cont">
            {% if appointment.report %}
                <div class="info_container">
                    <h3>Дијагноза</h3>
                    <div class="pers_info">
                        {{ appointment.report.diagnosis }}
                    </div>
                    <h3>Терапија:</h3>
                    <div class="pers_info">
                        {{ appointment.report.therapy }}
                    </div>
                    <h3>Забелешка:</h3>
                    <div class="pers_info">
                        {{ appointment.report.remark }}
                    </div>
                </div>
                {% if appointment.doctor.id == request.user.doctor.id %}
                    <div style="color: darkred" id="delete_report">
                        <i>ИЗБРИШИ ИЗВЕШТАЈ</i>
                    </div>
                {% endif %}
            {% else %}
                {% if request.user.doctor.id == appointment.doctor.id %}
                    <div>
                        <a href="{% url 'doctor:add_report' doctor_id=appointment.doctor.id appointment_id=appointment.id %}">Додај
                            извештај...</a>
                    </div>
                {% endif %}
            {% endif %}
        </div>

    </div>
</div>

<script>
    $(document).ready(function () {
         $('#delete_report').on('click', function () {
             $.ajax({
                 url: '{% url 'doctor:remove_report' %}',
                 data: {
                     'appointment_id': '{{ appointment.id }}'
                 },
                 dataType: 'json',
                 success: function (response) {
                     if (response['response'] == 'Success') {
                         location.reload();
                     } else {
                         alert('Oops, something went wrong!');
                     }
                 }
             });
         });
    });
</script>

</body>
</html>

doctor/templates/doctor/homepage_doctor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Bravo. It worked. This is the login page of a doctor!!!</h1>
<h2>Your user name is {{ username }}</h2>
<h3>Your password is {{ password }}</h3>
<h3>Your doctor ID is {{ doc_ID }}</h3>

<div>
    <h4>Лични информации</h4>
    Име: {{ request.user.doctor.name }} <br>
    Презиме: {{ request.user.doctor.surname }} <br>
    Докторска идентификација: {{ request.user.doctor.doctor_id }} <br>
    Everything else...
</div>

<div>
    <h4>Специјализација</h4>
    {% if request.user.doctor.is_general_practitioner %}
        Матичен доктор
    {% else %}
        Специјалист (да наведеме некако специјализации...)
    {% endif %}
</div>

<div>
    <h4>Пациенти</h4>
    Број на пациенти: {{ patient_count }}

</div>


<button>
    <a href="{% url 'doctor:patients_preview' doctor_id=request.user.id %}">
        Преглед на пациенти
    </a>
</button>
<div>
    <button>
        <a href="{% url 'doctor:make_appointment' doctor_id=request.user.id %}">
            Make appointment
        </a>
    </button>
</div>
<button>
    <a href="{% url 'doctor:old_appointments' doctor_id=request.user.id %}">
        Стари прегледи
    </a>
</button>
<button>
    <a href="{% url 'doctor:upcoming_appointments' doctor_id=request.user.id %}">
        Претстојни прегледи
    </a>
</button>

<button>
    <a href="{% url 'login:logout_user' %}">
        Logout
    </a>
</button>
</body>
</html>

doctor/templates/doctor/old_appointments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Стари термини</title>
</head>
<body>
<h3>Термини на {{ doctor.name }} {{ doctor.surname }}</h3>
{% if appointments.count == 0 %}
    <div>
        <i>Историјата на термини е празна.</i>
    </div>
{% else %}
    <ul>
        {% for appointment in appointments %}
            <li>
                <div style="border: solid; color: mediumaquamarine;">
                    Број на термин: <b>{{ appointment.appointment_number }}</b><br/>
                    Пациент: <b>{{ appointment.patient }}</b><br/>
                    Датум: <b>{{ appointment.date }}</b><br/>
                    Време: <b>{{ appointment.time }}</b><br/>
                    <a href="{% url 'doctor:appointment_details' doctor_id=appointment.doctor.user.id appointment_id=appointment.id %}">Извештај</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endif %}
</body>
</html>

doctor/templates/doctor/patients_preview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пациенти</title>
</head>
<body>

<h3>Пациенти на {{ doctor.name }} {{ doctor.surname }}</h3>
<h2>Матични пациенти:</h2>
<ul>
    {% for patient in doctors_patients %}
        <li>
            <div>
                <a href={% url "doctor:patientDetails" request.user.id patient.user.id %}> {{ patient }} </a>
            </div>
        </li>
    {% endfor %}
</ul>
<h2>Пациенти без матичен доктор:</h2>
<ul>
    {% for patient in patients_without_gp %}
        <li>
            <div>
                <a href={% url "doctor:patientDetails" request.user.id patient.user.id %}> {{ patient }} </a>
            </div>
        </li>
    {% endfor %}
</ul>
</body>
</html>

doctor/templates/doctor/specialist_patient_preview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пациенти</title>
</head>
<body>

<h3>Пациенти на {{ doctor.name }} {{ doctor.surname }}</h3>
<h2>Прегледани пациенти:</h2>
<ul>
    {% for patient in doctors_patients %}
        <li>
            <div>
                <a href={% url "doctor:patientDetails" request.user.id patient.user.id %}> {{ patient }} </a>
            </div>
        </li>
    {% endfor %}
</ul>
{#<h2>Пациенти без матичен доктор:</h2>#}
{#<ul>#}
{#    {% for patient in patients_without_gp %}#}
{#        <li>#}
{#            <div>#}
{#                <a href={% url "doctor:patientDetails" request.user.id patient.user.id %}> {{ patient }} </a>#}
{#            </div>#}
{#        </li>#}
{#    {% endfor %}#}
{#</ul>#}
</body>
</html>

doctor/templates/doctor/upcoming_appointments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Закажани термини</title>
</head>
<body>
<h3>Закажани термини на {{ doctor.name }} {{ doctor.surname }}</h3>
{% if appointments.count == 0 %}
    <div>
        <i>Немате закажани термини</i>
    </div>
{% else %}
    <ul>
        {% for appointment in appointments %}
            <li>
                <div style="border: solid; color: mediumaquamarine;">
                    Број на термин: <b>{{ appointment.appointment_number }}</b><br/>
                    Пациент: <b>{{ appointment.patient }}</b><br/>
                    Датум: <b>{{ appointment.date }}</b><br/>
                    Време: <b>{{ appointment.time }}</b><br/>
                    <a href="{% url 'doctor:appointment_details' doctor_id=appointment.doctor.user.id appointment_id=appointment.id %}">Извештај</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endif %}
</body>
</html>