ezdravstvo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls', namespace="login")),
    url(r'^', include('patient.urls', namespace="patient")),
    url(r'^', include('doctor.urls', namespace="doctor"))
]

login/urls.py
from django.conf.urls import url

from login import utils
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.UserFormView.as_view(), name='index'),
    url(r'^welcome/$', views.homepage, name='homepage'),
    url(r'^logout/$', views.logout_view, name='logout_user'),
    url(r'^registerPatient/$', views.PatientRegistrationView.as_view(), name='register_patient'),
    url(r'^registerDoctor/$', views.DoctorRegistrationView.as_view(), name='register_doctor'),
    url(r'^ajax/get_gps_for_hospital/$', utils.get_gps_for_hospital, name='get_gps_for_hospital'),
    url(r'^ajax/change_user_password/$', utils.change_user_password, name='change_user_password'),
]

patient/urls.py
from django.conf.urls import url

from patient import utils
from . import views

app_name = 'patient'
urlpatterns = [
    url(r'^patient/(?P<patient_id>[0-9]+)/$', views.homepage, name='homepage'),
    url(r'^patient/(?P<patient_id>[0-9]+)/homepage/$', views.homepage, name='homepage'),
    url(r'^patient/(?P<patient_id>[0-9]+)/oldAppointments/$', views.old_appointments, name='old_appointments'),
    url(r'^patient/(?P<patient_id>[0-9]+)/upcomingAppointments', views.upcoming_appointments, name='upcoming_appointments'),
    url(r'^patient/(?P<patient_id>[0-9]+)/appointment/(?P<appointment_id>[0-9]+)/$', views.appointment_details, name='appointment_details'),
    url(r'^ajax/get_patient_personal_info/$', utils.get_patient_personal_info, name='get_patient_personal_info'),
    url(r'^ajax/get_old_appointments/$', utils.get_old_appointments, name='get_old_appointments'),
    url(r'^ajax/get_upcoming_appointments/$', utils.get_upcoming_appointments, name='get_upcoming_appointments'),
    url(r'^ajax/patient_apps_list/$', utils.get_patient_apps_list, name='patient_apps_list')
]

patient/models.py
from django.db import models

# Create your models here.

patient/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render

# Create your views here.
from login.models import Patient, Report, Appointment


@login_required(login_url='login:index')
def homepage(request, patient_id):
    # TODO Check patient_id == user_id
    patient = Patient.objects.get(user__pk=request.user.id)
    old_appointments1 = patient.appointment_set.exclude(has_report_added=False)
    upcoming_appointments1 = patient.appointment_set.filter(has_report_added=False)
    return render(request, 'patient/homepage.html', {
        'patient': patient,
        'old_appointments': old_appointments1,
        'upcoming_appointments': upcoming_appointments1
    })


@login_required(login_url='login:index')
def old_appointments(request, patient_id):
    patient = Patient.objects.get(user__pk=request.user.id)
    appointments = patient.appointment_set.exclude(has_report_added=False)
    return render(request, 'patient/old_appointments.html', {'appointments': appointments,
                                                             'patient': patient})


@login_required(login_url='login:index')
def upcoming_appointments(request, patient_id):
    patient = Patient.objects.get(user__pk=request.user.id)
    appointments = patient.appointment_set.filter(has_report_added=False)
    return render(request, 'patient/upcoming_appointments.html', {'patient': patient,
                                                                  'appointments': appointments})


@login_required(login_url='login:index')
def appointment_details(request, patient_id, appointment_id):
    try:
        appointment = Appointment.objects.get(pk=appointment_id)
        if appointment.patient.user.id == request.user.id:
            return render(request, 'patient/appointment_details.html', {'appointment': appointment})
        else:
            raise Http404("Извештајот не постои")
    except Report.DoesNotExist:
        raise Http404("Извештајот не постои")

patient/templates/patient/appointment_details.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'patient/patient_style.css' %}"/>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Преглед #{{ appointment.appointment_number }}</title>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="//rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css"/>
</head>
<body>

<div id="body_container">

    <div id="toolbar">
        <div style="display: inline-block; width: 31%;" >
            <h1 style="padding-left: 30px; color: darkblue">{{ request.user.patient.name }} {{ request.user.patient.surname }}</h1>
        </div>

        <div class="toolbar_links">
            <button onClick="javascript:history.go(-1);" style="float: right;">
                    Назад
            </button>
        </div>

        <div class="toolbar_links" style="width: 22%;">
            <button id="btn_change_password" onclick="open_popup()" style="float: right;">
                    Промени лозинка
            </button>
        </div>
        <div class="toolbar_links" style="width: 20%">
            <a href="{% url 'login:logout_user' %}"><button style="display: block;">Одјави се</button></a>
        </div>
    </div>

    <div id="information_container">
        <h2>Детали за преглед #{{ appointment.appointment_number }}</h2>
        <div class="app_cont">
            <h3>Информации за пациентот</h3>

            <div>
                <div class="info_container">
                    <div class = "label_info"> Пациент: </div>
                    <div class="pers_info"> {{ appointment.patient }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Матичен број: </div>
                    <div class="pers_info"> {{ appointment.patient.ssn }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Датум на раѓање: </div>
                    <div class="pers_info"> {{ appointment.patient.date_of_birth }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Адреса на живеење: </div>
                    <div class="pers_info"> {{ appointment.patient.address }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Матичен доктор: </div>
                    <div class="pers_info">
                        {% if appointment.patient.general_practitioner %}
                            {{ appointment.patient.general_practitioner }}
                        {% else %}
                            Нема
                        {% endif %}
                    </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Задолжен доктор за прегледот: </div>
                    <div class="pers_info"> {{ appointment.doctor }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Датум: </div>
                    <div class="pers_info"> {{ appointment.date }} </div>
                </div>
                <div class="info_container">
                    <div class = "label_info"> Час: </div>
                    <div class="pers_info"> {{ appointment.time }} </div>
                </div>


            </div>
        </div>
        <div class="app_cont">
            {% if appointment.report %}
            <div>
                <h3>Дијагноза</h3>
                <div class="info_container">
                    <div class = "label_info" style="font-weight: bold;"> {{ appointment.report.diagnosis }} </div>
                </div>

                <h3>Терапија:</h3>
                <div class="info_container">
                    <div class = "label_info" style="font-weight: bold;"> {{ appointment.report.therapy }} </div>
                </div>

                <h3>Забелешка:</h3>
                <div class="info_container">
                    <div class = "label_info" style="font-weight: bold;"> {{ appointment.report.remark }} </div>
                </div>
            </div>
            {% endif %}
        </div>

    </div>
</div>

<script>
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    function validate() {
        var old_pass = $('#old_pass').val();
        var new_pass = $('#new_pass').val();
        var confirm_pass = $('#confirm_pass').val();
        if (old_pass.trim() == "" || new_pass.trim() == "" || confirm_pass == "") {
            $('#error_text').html("Мора да ги внесете сите полиња!");
            return false;
        }
        if (new_pass != confirm_pass) {
            $('#error_text').html("Новата лозинка не поклопува со потврдата!");
            return false;
        }
        return true;
    }

    function open_popup() {
        w2popup.open({
            title: 'Промена на лозинка',
            body: "Стара лозинка: <input type=\"password\" id=\"old_pass\"><br/><br/>\n" +
            "Нова лозинка: <input type=\"password\" id=\"new_pass\"><br/><br/>\n" +
            "Потврдете лозинка: <input type=\"password\" id=\"confirm_pass\"><br/><br/>\n" +
            "<div id=\"error_text\" style=\"color:red;\"></div><br/>" +
            "<button id=\"btn_confirm\">Потврди</button>"
        });
        $('#btn_confirm').on('click', function (event) {
            console.log("Pressed");
            if (validate()) {
                var old_pass = $('#old_pass').val();
                var new_pass = $('#new_pass').val();
                var confirm_pass = $('#confirm_pass').val();
                attempt_change_password(old_pass, new_pass, confirm_pass);
            }
        });
    }

    function go_to_login() {
        location.href = '{% url 'login:index' %}';
    }

    function attempt_change_password(old_password, new_password, confirm_password) {
        var csrftoken = getCookie('csrftoken');
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $.ajax({
            type: 'POST',
            url: '{% url 'login:change_user_password' %}',
            data: {
                'old_password': old_password,
                'new_password': new_password,
                'confirm_password': confirm_password
            },
            dataType: 'json',
            success: function (response) {
                if (response.hasOwnProperty('error')) {
                    alert(response['error'])
                } else {
                    go_to_login();
                }
            }
        });
    }
</script>

</body>
</html>

patient/templates/patient/old_appointments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Стари термини</title>
</head>
<body>
<h3>Термини на {{ patient.name }} {{ patient.surname }}</h3>
{% if appointments.count == 0 %}
    <div>
        <i>Историјата на термини е празна.</i>
    </div>
{% else %}
    <ul>
        {% for appointment in appointments %}
            <li>
                <div style="border: solid; color: mediumaquamarine;">
                    Број на термин: <b>{{ appointment.appointment_number }}</b><br/>
                    Доктор: <b>{{ appointment.doctor }}</b><br/>
                    Датум: <b>{{ appointment.date }}</b><br/>
                    Време: <b>{{ appointment.time }}</b><br/>
                    <a href="{% url 'patient:appointment_details' patient_id=appointment.patient.user.id appointment_id=appointment.id %}">Извештај</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endif %}
</body>
</html>

patient/templates/patient/upcoming_appointments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Закажани термини</title>
</head>
<body>
<h3>Закажани термини на {{ patient.name }} {{ patient.surname }}</h3>
{% if appointments.count == 0 %}
    <div>
        <i>Немате закажани термини.</i>
    </div>
{% else %}
    <ul>
        {% for appointment in appointments %}
            <li>
                <div style="border: solid; color: mediumaquamarine;">
                    Број на термин: <b>{{ appointment.appointment_number }}</b><br/>
                    Доктор: <b>{{ appointment.doctor }}</b><br/>
                    Датум: <b>{{ appointment.date }}</b><br/>
                    Време: <b>{{ appointment.time }}</b><br/>
                    <a href="{% url 'patient:appointment_details' patient_id=appointment.patient.user.id appointment_id=appointment.id %}">Извештај</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endif %}
</body>
</html>